[workspace]
members = [
    "src/agent-client-protocol",
]
resolver = "2"

[workspace.package]
authors = ["Zed <hi@zed.dev>"]
edition = "2024"
license = "Apache-2.0"
repository = "https://github.com/agentclientprotocol/rust-sdk"
homepage = "https://github.com/agentclientprotocol/rust-sdk"
